build:
	@docker build . --tag $${IMAGE_TO_BUILD}:local

clean:
	@docker rmi $${IMAGE_TO_BUILD}:local || true

upstream:
	echo "FROM frison/$${IMAGE_TO_BUILD}:latest" > Dockerfile
	rm -rf files/

test:
	echo "FROM frison/$${IMAGE_TO_BUILD}:latest"

.PHONY: build clean upstream
