name: "Publish Image to Dockerhub"
description: "Publish to dockerhub with multiplatform support"

inputs:
  dockerhub-username:
    description: "The dockerhub username to authenticate with and push the image to"
    required: true
  dockerhub-token:
    description: "The dockerhub token to authenticate with and push the image to"
    required: true
  dockerfile:
    description: "The dockerfile to build the image from"
    required: true
  platforms:
    description: "The platforms to build the image for"
    required: true
  build-target:
    description: "The build target to build the image for"
    required: true
runs:
  using: "composite"
  steps:
    # https://github.com/docker/login-action
    -
      name: 🗝 Log into Dockerhub
      uses: docker/login-action@v2
      with:
        username:  ${{ inputs.dockerhub-username }}
        password:  ${{ inputs.dockerhub-token }}

    -
      name: 🤔 Set image and tag prefix variables
      shell: bash
      run: |

        # We use 3-step GITHUB_ENV setting so that the variables are available to the next lines as a consistent
        # practice. This is because changes to the GITHUB_ENV file is not available until after the step.

        # Splits the build target and uses the last part as the tag prefix
        # ie. 'dev/rails-71' -> 'rails-71'
        echo -n "TAG_PREFIX=" >> $GITHUB_ENV
        TAG_PREFIX=$(basename "${{ inputs.build-target }}")
        echo ${TAG_PREFIX} >> $GITHUB_ENV

        # Splits the build target and uses everything but the tag prefix as the image name
        # ie. 'dev/rails-71' -> dev'
        echo -n "IMAGE=" >> $GITHUB_ENV
        IMAGE=$(dirname "${{ inputs.build-target }}")
        echo ${IMAGE} >> $GITHUB_ENV

        # The composite dockerfile will be named after the image
        # ie. 'dev/rails-71' -> Docker.composite.dev
        DOCKERFILE=Dockerfile.composite.${IMAGE}
        echo "DOCKERFILE=${DOCKERFILE}" >> $GITHUB_ENV

        # In multistage builds, images cannot be referenced with stage names that start with a number or contain symbols.
        # So because we can't have
        #   FROM x AS dev/rails-71
        # as a stage name, as a consequence of this when the stage name is generated in the composite dockerfile
        # it will be of the form 'dev_rails-71' instead of 'dev/rails-71'
        BUILD_TARGET="${IMAGE}_${TAG_PREFIX}"
        echo "BUILD_TARGET=${BUILD_TARGET}" >> $GITHUB_ENV

    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    # This is an architecture emulator that claims to provide near-native speeds for multi-arch builds, however
    # build rails for arm64 on an amd64 machine timed out after 6 hours -- so I'm not convinced I believe that claim.
    -
      name: 🛠 Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ inputs.platforms }}

    -
      name: 🛠 Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: ${{ inputs.platforms }}

    -
      name: 🔨 Generate dockerfile
      shell: bash
      run: |
        make composite-dockerfile

    # https://github.com/docker/metadata-action
    -
      name: 🐳 Generate Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.dockerhub-username }}/${{ env.IMAGE }}
        tags: |
          # On main: push `[:image directory:]/[:tag directory:]`.
          # Always: push `[:image directory:]/[:tag directory:]-edge`.
          # On tag: push `[:image directory:]/[:tag directory:]-[:tag]`.
          # Always: push `[:image directory:]/[:tag directory:]-[:short_sha (7 chars)]`.
          type=raw,value=${{ env.TAG_PREFIX }},priority=1000,enable={{is_default_branch}}
          type=raw,value=edge,prefix=${{ env.TAG_PREFIX }}-,priority=700
          type=ref,enable=true,priority=600,prefix=${{ env.TAG_PREFIX }}-,suffix=,event=tag
          type=sha,enable=true,priority=100,prefix=${{ env.TAG_PREFIX }}-,suffix=,format=short

    # https://github.com/docker/build-push-action
    -
      name: 🔨🚀🐳 ${{ inputs.build-target }} (${{ inputs.platforms }})
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ env.DOCKERFILE }}
        platforms: ${{ inputs.platforms }}
        target: ${{ env.BUILD_TARGET }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-to: |
          type=gha,mode=max
        cache-from: |
          type=gha,mode=max
          type=registry,ref=${{ inputs.dockerhub-username }}/${{ env.IMAGE }}:${{ env.TAG_PREFIX }},mode=max

